# =============================================================================
# data_format_ablation.R
# -----------------------------------------------------------------------------
# "Data-format ablation" experiment on the real dataset.
#
# For every pathogen that has at least MIN_DATASETS_PER_ARM datasets of
# individual-level format (summary types 4/5: exact or interval-censored
# frequency tables) AND at least MIN_DATASETS_PER_ARM datasets of summary-
# statistic format (types 1/2/3: median+range, median+IQR, mean+SD), the
# script fits three model versions:
#
#   A. Individual-level only   — summary types 4 and 5 only
#   B. Summary-statistics only — summary types 1, 2, and 3 only
#   C. Federated / full model  — all available data formats jointly
#
# Comparison metrics (per pathogen × distribution):
#
#   Posterior summaries (all three arms)
#     pred_median   posterior predictive median (days): median (2.5%, 97.5%)
#     pred_q95      posterior predictive 95th percentile (days)
#     tau           between-study SD: median (2.5%, 97.5%); "— (n<5)" when sparse
#
#   Uncertainty
#     width            95% CrI width of pred_median (posterior uncertainty)
#     interval_ratio   A_width / C_width and B_width / C_width; > 1 = federated is
#                      tighter
#     norm_shift       (C_median − arm_median) / arm_width; normalised shift in units
#                      of arm's own uncertainty (|shift| > 0.5 = meaningful pull)
#
#   Distributional discrepancy (posterior-median predictive CDFs)
#     W2       Wasserstein-2 distance (days); quantile-function L2 over [0.1%, 99.9%]
#     JS       Jensen-Shannon divergence (bits, base-2); symmetric, bounded [0, 1]
#     OVL      Overlap coefficient ∫ min(f_A, f_C) dx; 1 = identical, 0 = disjoint
#
#   Tail probabilities  P(T > d | arm) at TAIL_THRESHOLDS (days)
#     ptail_d_A, ptail_d_B, ptail_d_C   (one triplet per threshold)
#
#   LOO/ELPD
#     elpd / elpd_se   study-level PSIS-LOO ELPD (NA when n_datasets < 4)
#     n_k_high         number of studies with Pareto k̂ > 0.7 (LOO reliability flag)
#
#   Differences  (federated minus single-arm, posterior-median point estimates)
#     delta_CA_median, delta_CA_q95
#     delta_CB_median, delta_CB_q95
#
# LOO/ELPD notes
# --------------
# log_lik[n_datasets * 3] is generated by the Stan model.  For types 1/2, the
# three entries per study are the individual order-statistic contributions; for
# types 3/4/5 only the first entry is used (unused slots are 0).  Summing each
# triplet gives a per-study log-likelihood matrix for study-level PSIS-LOO.
# ELPD values are comparable within an arm across distributions but NOT across
# arms — each arm conditions on a different number and type of observations.
#
# Distributional-metric notes
# ---------------------------
# W2, JS, and OVL are computed from the posterior-median predictive CDF, i.e.
# the CDF at the draw-wise median of the predictive distribution.  This is a
# single representative distribution, not a posterior average; it is consistent
# with how pred_median and pred_q95 are reported.  All three metrics compare
# two arms pairwise: (A, C), (B, C), and (A, B).
#
# Output
# ------
#   results/data_format_ablation.rds  — nested list of stanfit objects + tables
#   results/data_format_ablation.csv  — main comparison table (wide format)
#
# Results file format:
#   $ablation_fits[[pathogen]][[arm]][[dist]]
#     $fit        rstan stanfit object (NULL if sampling failed)
#     $stan_data  list passed to Stan
#     $datasets   dataset list used for this arm
#     $skipped    TRUE + $reason when deliberately skipped
#   $comparison_tbl  data.frame with all comparison columns
# =============================================================================

devtools::load_all(here::here(), quiet = TRUE)

local({
  pkg_datasets <- grep("^datasets_", ls(asNamespace("ddsynth")), value = TRUE)
  stale <- intersect(ls(envir = .GlobalEnv), pkg_datasets)
  if (length(stale) > 0L) {
    message("Removing ", length(stale), " stale dataset object(s) from .GlobalEnv: ",
            paste(stale, collapse = ", "))
    rm(list = stale, envir = .GlobalEnv)
  }
})

library(rstan)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())


# ── 1. Settings ───────────────────────────────────────────────────────────────

CHAINS  <- 4
ITER    <- 12000
WARMUP  <- 2000
THIN    <- 1
SEED    <- 123
CONTROL <- list(adapt_delta = 0.999, max_treedepth = 12, stepsize = 0.01)

DIST_CODES <- c(lognormal = 1L, gamma = 2L, weibull = 3L, burr = 4L, gengamma = 5L)

# Minimum datasets required in both arms before fitting.
MIN_DATASETS_PER_ARM <- 2L

# Tail-probability thresholds (days) for P(T > d | arm).
TAIL_THRESHOLDS <- c(7, 14, 21)

# Set FALSE to skip distributional metrics (W2/JS/OVL/tail) after fitting —
# useful for a quick tabular run when the CDFs are expensive to compute.
COMPUTE_CDF_METRICS <- TRUE

# Number of posterior draws used inside compute_predictive_cdf().
# Higher = more accurate; 200 is a reasonable trade-off for a comparison run.
N_CDF_DRAWS <- 200

# Pathogens to wipe and refit from scratch.
FORCE_RERUN <- character(0)

CI_PROBS <- c(0.025, 0.5, 0.975)


# ── 2. Output paths ───────────────────────────────────────────────────────────

OUTPUT_DIR  <- here::here("results")
OUTPUT_FILE <- file.path(OUTPUT_DIR, "data_format_ablation.rds")
CSV_FILE    <- file.path(OUTPUT_DIR, "data_format_ablation.csv")
dir.create(OUTPUT_DIR, showWarnings = FALSE)


# ── 3. Pathogen registry ──────────────────────────────────────────────────────

pathogen_registry <- list(
  Nipah    = datasets_Nipah,
  MVD      = datasets_MVD,
  EVD      = datasets_EVD,
  Lassa    = datasets_Lassa,
  SARS     = datasets_SARS,
  MERS     = datasets_MERS,
  Zika     = datasets_Zika,
  Measles  = datasets_Measles,
  Mpox     = datasets_Mpox,
  Cholera  = datasets_Cholera,
  RVF      = datasets_RVF,
  CCHF     = datasets_CCHF_extended,
  COVID_19 = datasets_COVID_19,
  Dengue   = datasets_Dengue,
  YFV      = datasets_YFV,
  Typhoid  = datasets_typhoid,
  Smallpox = datasets_Smallpox,
  Flu      = datasets_flu
)


# ── 4. Dataset classification helpers ────────────────────────────────────────

.get_summary_type <- function(d) {
  if (!is.null(d$freq_lower) && !is.null(d$freq_upper) && !is.null(d$freq_count)) 5L
  else if (!is.null(d$freq_value) && !is.null(d$freq_count)) 4L
  else if (!is.null(d$mean) && !is.null(d$sd)) 3L
  else if (!is.null(d$median) && !is.null(d$Q1) && !is.null(d$Q3)) 2L
  else if (!is.null(d$median) && (!is.null(d$min) || !is.null(d$max))) 1L
  else NA_integer_
}

.make_arms <- function(datasets) {
  types <- vapply(datasets, .get_summary_type, integer(1L))
  list(
    individual_only = datasets[!is.na(types) & types %in% c(4L, 5L)],
    summary_only    = datasets[!is.na(types) & types %in% c(1L, 2L, 3L)],
    federated       = datasets
  )
}

# compute_predictive_cdf() uses "gg" for generalised gamma; all others match.
.cdf_dist_name <- function(dist_name) {
  if (dist_name == "gengamma") "gg" else dist_name
}


# ── 5. Identify eligible pathogens ───────────────────────────────────────────

eligible_pathogens <- Filter(function(ds) {
  arms <- .make_arms(ds)
  length(arms$individual_only) >= MIN_DATASETS_PER_ARM &&
    length(arms$summary_only)  >= MIN_DATASETS_PER_ARM
}, pathogen_registry)

if (length(eligible_pathogens) == 0L)
  stop("No pathogens meet the eligibility criterion (>= ", MIN_DATASETS_PER_ARM,
       " datasets per arm). Reduce MIN_DATASETS_PER_ARM.")

message("\n", strrep("=", 70))
message("Eligible pathogens for data-format ablation")
message("(require >= ", MIN_DATASETS_PER_ARM, " datasets per arm):")
message(sprintf("  %-12s  %9s  %10s  %7s",
                "Pathogen", "indiv (A)", "sumstat (B)", "total (C)"))
message(strrep("-", 46))
for (p in names(eligible_pathogens)) {
  arms <- .make_arms(eligible_pathogens[[p]])
  message(sprintf("  %-12s  %9d  %10d  %7d",
                  p, length(arms$individual_only),
                  length(arms$summary_only),
                  length(arms$federated)))
}
message(strrep("=", 70))


# ── 6. Compile Stan model ─────────────────────────────────────────────────────

stan_file <- system.file("stan",
                         "hierarchical_data_synthesis_summary_stats.stan",
                         package = "ddsynth")
if (!nzchar(stan_file))
  stop("Stan file 'hierarchical_data_synthesis_summary_stats.stan' not found.")
stan_model <- rstan::stan_model(stan_file)


# ── 7. Fitting helper ─────────────────────────────────────────────────────────

.fit_one <- function(datasets, dist_name, arm, pathogen) {
  dist_type <- DIST_CODES[[dist_name]]

  stan_data <- tryCatch(
    prepare_stan_data_from_datasets(datasets, dist_type = dist_type),
    error = function(e) {
      message("  [SKIP] prepare_stan_data failed for ",
              pathogen, "/", arm, "/", dist_name, ": ", conditionMessage(e))
      NULL
    }
  )
  if (is.null(stan_data)) return(NULL)
  stan_data <- update_phi_prior(stan_data, datasets)

  fit <- tryCatch(
    rstan::sampling(
      stan_model,
      data    = stan_data,
      chains  = CHAINS,
      iter    = ITER,
      warmup  = WARMUP,
      thin    = THIN,
      control = CONTROL,
      seed    = SEED,
      refresh = 200
    ),
    error = function(e) {
      message("  [FAIL] sampling failed for ",
              pathogen, "/", arm, "/", dist_name, ": ", conditionMessage(e))
      NULL
    }
  )

  list(fit = fit, stan_data = stan_data, datasets = datasets)
}


# ── 8. Load stored results ───────────────────────────────────────────────────

ablation_results <- if (file.exists(OUTPUT_FILE)) {
  message("Resuming from existing results: ", OUTPUT_FILE)
  readRDS(OUTPUT_FILE)$ablation_fits
} else {
  list()
}

if (length(FORCE_RERUN) > 0L) {
  unknown <- setdiff(FORCE_RERUN, names(eligible_pathogens))
  if (length(unknown) > 0L)
    warning("FORCE_RERUN contains unrecognised pathogen(s): ",
            paste(unknown, collapse = ", "), call. = FALSE)
  for (p in intersect(FORCE_RERUN, names(ablation_results))) {
    message("Force-rerun: clearing stored results for '", p, "'.")
    ablation_results[[p]] <- NULL
  }
}


# ── 9. Main fitting loop ──────────────────────────────────────────────────────

ARM_LABELS <- c("individual_only", "summary_only", "federated")

for (pathogen in names(eligible_pathogens)) {

  message("\n", strrep("=", 70))
  message("PATHOGEN: ", pathogen)
  message(strrep("=", 70))

  if (is.null(ablation_results[[pathogen]]))
    ablation_results[[pathogen]] <- list()

  arms <- .make_arms(eligible_pathogens[[pathogen]])

  all_done <- all(vapply(ARM_LABELS, function(arm) {
    all(vapply(names(DIST_CODES), function(d) {
      !is.null(ablation_results[[pathogen]][[arm]][[d]])
    }, logical(1L)))
  }, logical(1L)))

  if (all_done) {
    message("  All fits already complete — nothing new to do.")
    next
  }

  for (arm in ARM_LABELS) {

    arm_datasets <- arms[[arm]]

    if (is.null(ablation_results[[pathogen]][[arm]]))
      ablation_results[[pathogen]][[arm]] <- list()

    n_arm <- length(arm_datasets)
    if (n_arm < MIN_DATASETS_PER_ARM) {
      message("\n  [SKIP] ", arm, ": only ", n_arm,
              " dataset(s) (min = ", MIN_DATASETS_PER_ARM, ").")
      next
    }

    message("\n  Arm: ", arm, "  (n_datasets = ", n_arm, ")")

    for (dist_name in names(DIST_CODES)) {

      if (!is.null(ablation_results[[pathogen]][[arm]][[dist_name]])) {
        message("  [SKIP] ", pathogen, " / ", arm, " / ", dist_name,
                " — already in results.")
        next
      }

      if (dist_name == "gengamma" &&
          !should_attempt_gg(arm_datasets, verbose = FALSE)) {
        message("  [SKIP] ", pathogen, " / ", arm,
                " / gengamma — identifiability heuristic.")
        ablation_results[[pathogen]][[arm]][["gengamma"]] <-
          list(skipped = TRUE, reason = "identifiability_heuristic",
               datasets = arm_datasets)
        next
      }

      if (dist_name == "gamma" &&
          !gamma_type2_reliable(arm_datasets, verbose = FALSE)) {
        message("  [SKIP] ", pathogen, " / ", arm,
                " / gamma — gamma_type2_reliable check.")
        ablation_results[[pathogen]][[arm]][["gamma"]] <-
          list(skipped = TRUE, reason = "gamma_type2_reliable",
               datasets = arm_datasets)
        next
      }

      message("  Fitting: ", pathogen, " | ", arm, " | ", dist_name)
      ablation_results[[pathogen]][[arm]][[dist_name]] <-
        .fit_one(arm_datasets, dist_name, arm, pathogen)
    }
  }

  saveRDS(list(ablation_fits = ablation_results), OUTPUT_FILE)
  message("\n  Saved to: ", OUTPUT_FILE)
}

message("\n", strrep("=", 70))
message("Fitting complete.")
message(strrep("=", 70))


# ── 10. Summary extraction helpers ───────────────────────────────────────────

# Study-level PSIS-LOO ELPD using the log_lik triplets from Stan.
# Returns list(elpd, se, n_k_high) — all NA/0 on failure or when n < 4.
.compute_loo_elpd <- function(fit, n_datasets) {
  na_res <- list(elpd = NA_real_, se = NA_real_, n_k_high = NA_integer_)
  if (is.null(fit) || n_datasets < 4L) return(na_res)

  ll_raw <- tryCatch(
    rstan::extract(fit, pars = "log_lik")$log_lik,
    error = function(e) NULL
  )
  if (is.null(ll_raw) || ncol(ll_raw) != n_datasets * 3L) return(na_res)

  n_draws <- nrow(ll_raw)
  ll_per_study <- matrix(0, nrow = n_draws, ncol = n_datasets)
  for (d in seq_len(n_datasets)) {
    base <- (d - 1L) * 3L + 1L
    ll_per_study[, d] <- ll_raw[, base] + ll_raw[, base + 1L] + ll_raw[, base + 2L]
  }
  ll_per_study[!is.finite(ll_per_study)] <- -700

  loo_res <- tryCatch(
    loo::loo(ll_per_study, r_eff = rep(1, n_datasets)),
    error = function(e) NULL
  )
  if (is.null(loo_res)) return(na_res)

  n_k_high <- sum(loo_res$diagnostics$pareto_k > 0.7, na.rm = TRUE)

  list(
    elpd     = loo_res$estimates["elpd_loo", "Estimate"],
    se       = loo_res$estimates["elpd_loo", "SE"],
    n_k_high = n_k_high
  )
}

# Format a posterior sample vector as "median (lo, hi)".
.fmt <- function(x, digits = 2L) {
  x <- x[is.finite(x)]
  if (length(x) == 0L) return(NA_character_)
  q <- quantile(x, CI_PROBS)
  sprintf("%.*f (%.*f, %.*f)", digits, q[2L], digits, q[1L], digits, q[3L])
}

# Extract posterior summaries and LOO from one arm's result slot.
.extract_summaries <- function(res) {
  if (is.null(res) || isTRUE(res$skipped) || is.null(res$fit)) return(NULL)
  sims <- tryCatch(rstan::extract(res$fit), error = function(e) NULL)
  if (is.null(sims)) return(NULL)

  n_datasets  <- length(res$datasets)
  pm          <- sims$pred_median[is.finite(sims$pred_median)]
  pq          <- sims$pred_q95[is.finite(sims$pred_q95)]
  tau_raw     <- if (n_datasets >= 5L) sims$tau else NULL
  loo_res     <- .compute_loo_elpd(res$fit, n_datasets)

  list(
    pred_median_fmt   = .fmt(pm, 1L),
    pred_q95_fmt      = .fmt(pq, 1L),
    pred_median_med   = median(pm),
    pred_q95_med      = median(pq),
    pred_median_width = diff(quantile(pm, c(0.025, 0.975))),
    tau_fmt           = if (!is.null(tau_raw)) .fmt(tau_raw, 2L) else "— (n<5)",
    tau_med           = if (!is.null(tau_raw)) median(tau_raw)   else NA_real_,
    elpd              = loo_res$elpd,
    elpd_se           = loo_res$se,
    n_k_high          = loo_res$n_k_high,
    n_datasets        = n_datasets
  )
}

# Compute distributional metrics between two posterior-median predictive CDFs.
#
# Uses the posterior-median CDF (the draw whose CDF is closest to the
# median across all draws) as a single representative distribution.  W2 is
# in the same units as the outcome (days); JS is in bits (base-2).  OVL is
# the overlap coefficient ∫ min(f_ref, f_arm) dx ∈ [0, 1].
#
# Also returns tail probabilities P(T > d) at each threshold in thr_days.
# Returns NULL when either fit is absent or CDF computation fails.
.compute_dist_metrics <- function(fit_ref, fit_arm, dist_name,
                                  thr_days = TAIL_THRESHOLDS) {
  if (is.null(fit_ref) || is.null(fit_arm)) return(NULL)

  cdf_name <- .cdf_dist_name(dist_name)

  # Determine x upper bound from the upper tail of pred_q95 across both fits.
  .q99_pred_q95 <- function(f) {
    s <- tryCatch(rstan::extract(f, pars = "pred_q95")$pred_q95, error = function(e) NULL)
    if (is.null(s) || length(s) == 0L) return(30)
    quantile(s[is.finite(s)], 0.99, na.rm = TRUE)
  }
  x_max <- max(.q99_pred_q95(fit_ref), .q99_pred_q95(fit_arm)) * 1.1
  x_max <- max(x_max, max(thr_days) * 1.2, 14)

  x_seq <- seq(0.001, x_max, length.out = 1000L)

  cdf_ref_obj <- tryCatch(
    compute_predictive_cdf(fit_ref, cdf_name, x_seq = x_seq, n_draws = N_CDF_DRAWS),
    error = function(e) NULL
  )
  cdf_arm_obj <- tryCatch(
    compute_predictive_cdf(fit_arm, cdf_name, x_seq = x_seq, n_draws = N_CDF_DRAWS),
    error = function(e) NULL
  )
  if (is.null(cdf_ref_obj) || is.null(cdf_arm_obj)) return(NULL)

  # Posterior-median CDF: clamp to [ε, 1−ε] for numerical stability.
  F_ref <- pmax(pmin(cdf_ref_obj$summary$median, 1 - 1e-9), 1e-9)
  F_arm <- pmax(pmin(cdf_arm_obj$summary$median, 1 - 1e-9), 1e-9)

  dx <- diff(x_seq)[1L]

  # PDF via forward differences; renormalise to guard against CDF
  # non-monotonicity from interpolation artefacts.
  .cdf_to_pdf <- function(F) {
    f <- c(diff(F), 0) / dx
    f <- pmax(f, 1e-12)
    f / (sum(f) * dx)
  }
  f_ref <- .cdf_to_pdf(F_ref)
  f_arm <- .cdf_to_pdf(F_arm)

  # Jensen-Shannon divergence (bits, symmetric, bounded [0, 1])
  f_mix  <- 0.5 * (f_ref + f_arm)
  JS     <- 0.5 * sum(f_ref * log2(f_ref / f_mix) * dx, na.rm = TRUE) +
            0.5 * sum(f_arm * log2(f_arm / f_mix) * dx, na.rm = TRUE)
  JS     <- pmax(JS, 0)  # guard against tiny negative values from numerics

  # Overlap coefficient
  OVL <- sum(pmin(f_ref, f_arm) * dx, na.rm = TRUE)

  # Wasserstein-2 via quantile-function L2 norm
  # Q(p) = inf{x : F(x) >= p} approximated by linear interpolation.
  p_grid <- seq(0.001, 0.999, length.out = 500L)
  .quantile_fun <- function(F_vals) {
    sapply(p_grid, function(p) {
      idx <- which(F_vals >= p)[1L]
      if (is.na(idx)) return(x_seq[length(x_seq)])
      if (idx == 1L)  return(x_seq[1L])
      # Linear interpolation between grid points
      x_seq[idx - 1L] +
        (p - F_vals[idx - 1L]) / (F_vals[idx] - F_vals[idx - 1L]) *
        (x_seq[idx] - x_seq[idx - 1L])
    })
  }
  Q_ref <- .quantile_fun(F_ref)
  Q_arm <- .quantile_fun(F_arm)
  W2    <- sqrt(mean((Q_ref - Q_arm)^2, na.rm = TRUE))

  # Tail probabilities P(T > d) = 1 - F(d) at each threshold.
  .tail_prob <- function(F_vals, d) {
    idx <- which(x_seq >= d)[1L]
    if (is.na(idx)) return(0)
    1 - F_vals[idx]
  }
  tail_ref <- setNames(sapply(thr_days, .tail_prob, F_vals = F_ref), paste0("d", thr_days))
  tail_arm <- setNames(sapply(thr_days, .tail_prob, F_vals = F_arm), paste0("d", thr_days))

  list(
    W2       = round(W2,  3L),
    JS       = round(JS,  4L),
    OVL      = round(OVL, 4L),
    tail_ref = tail_ref,
    tail_arm = tail_arm
  )
}


# ── 11. Build comparison table ────────────────────────────────────────────────

dist_labels <- c(
  lognormal = "Log-normal", gamma = "Gamma",   weibull = "Weibull",
  burr      = "Burr XII",   gengamma = "Gen. gamma"
)

rows <- list()

for (pathogen in names(eligible_pathogens)) {
  for (dist_name in names(DIST_CODES)) {

    res_A <- ablation_results[[pathogen]][["individual_only"]][[dist_name]]
    res_B <- ablation_results[[pathogen]][["summary_only"]][[dist_name]]
    res_C <- ablation_results[[pathogen]][["federated"]][[dist_name]]

    s_A <- .extract_summaries(res_A)
    s_B <- .extract_summaries(res_B)
    s_C <- .extract_summaries(res_C)

    if (is.null(s_C)) next  # arm C is the reference; skip row if absent

    # ── Distributional metrics (if CDF computation is enabled) ────────────────
    dm_CA <- dm_CB <- dm_AB <- NULL
    if (COMPUTE_CDF_METRICS &&
        !is.null(res_C) && !isTRUE(res_C$skipped) && !is.null(res_C$fit)) {

      message("  Computing CDF metrics: ", pathogen, " / ", dist_name)

      if (!is.null(res_A) && !isTRUE(res_A$skipped) && !is.null(res_A$fit))
        dm_CA <- .compute_dist_metrics(res_C$fit, res_A$fit, dist_name)

      if (!is.null(res_B) && !isTRUE(res_B$skipped) && !is.null(res_B$fit))
        dm_CB <- .compute_dist_metrics(res_C$fit, res_B$fit, dist_name)

      if (!is.null(res_A) && !isTRUE(res_A$skipped) && !is.null(res_A$fit) &&
          !is.null(res_B) && !isTRUE(res_B$skipped) && !is.null(res_B$fit))
        dm_AB <- .compute_dist_metrics(res_A$fit, res_B$fit, dist_name)
    }

    # ── Helpers ───────────────────────────────────────────────────────────────
    .n <- function(res) {
      if (is.null(res) || isTRUE(res$skipped)) NA_integer_
      else length(res$datasets)
    }
    .delta <- function(s_ref, s_arm, field) {
      if (is.null(s_ref) || is.null(s_arm)) NA_real_
      else round(s_ref[[field]] - s_arm[[field]], 2L)
    }
    .ratio <- function(s_arm, s_ref) {
      # arm_width / ref_width; > 1 means arm is wider (federated is tighter)
      if (is.null(s_arm) || is.null(s_ref)) NA_real_
      else round(s_arm$pred_median_width / s_ref$pred_median_width, 3L)
    }
    .norm_shift <- function(s_arm, s_ref) {
      # (ref_median − arm_median) / arm_width
      if (is.null(s_arm) || is.null(s_ref)) NA_real_
      else round((s_ref$pred_median_med - s_arm$pred_median_med) /
                   s_arm$pred_median_width, 3L)
    }
    .dm_field <- function(dm, field) {
      if (is.null(dm)) NA_real_ else dm[[field]]
    }
    .tail <- function(dm, side, threshold) {
      # side = "tail_ref" (arm C) or "tail_arm" (the other arm)
      key <- paste0("d", threshold)
      if (is.null(dm) || is.null(dm[[side]])) NA_real_
      else round(dm[[side]][[key]], 4L)
    }

    # ── Tail probability columns ───────────────────────────────────────────────
    tail_cols <- list()
    for (d in TAIL_THRESHOLDS) {
      tail_cols[[paste0("ptail_A_", d)]] <- .tail(dm_CA, "tail_arm", d)
      tail_cols[[paste0("ptail_B_", d)]] <- .tail(dm_CB, "tail_arm", d)
      tail_cols[[paste0("ptail_C_", d)]] <- .tail(dm_CA, "tail_ref", d)
    }

    row <- c(
      list(
        pathogen  = pathogen,
        dist      = dist_labels[[dist_name]],
        n_indiv   = .n(res_A),
        n_sumstat = .n(res_B),
        n_total   = .n(res_C),

        # ── Arm A: individual-level only ─────────────────────────────────────
        A_pred_median = if (!is.null(s_A)) s_A$pred_median_fmt else NA_character_,
        A_pred_q95    = if (!is.null(s_A)) s_A$pred_q95_fmt    else NA_character_,
        A_tau         = if (!is.null(s_A)) s_A$tau_fmt         else NA_character_,
        A_width       = if (!is.null(s_A)) round(s_A$pred_median_width, 3L) else NA_real_,
        A_elpd        = if (!is.null(s_A) && !is.na(s_A$elpd)) round(s_A$elpd, 1L) else NA_real_,
        A_elpd_se     = if (!is.null(s_A) && !is.na(s_A$elpd_se)) round(s_A$elpd_se, 1L) else NA_real_,
        A_n_k_high    = if (!is.null(s_A)) s_A$n_k_high else NA_integer_,

        # ── Arm B: summary-statistics only ──────────────────────────────────
        B_pred_median = if (!is.null(s_B)) s_B$pred_median_fmt else NA_character_,
        B_pred_q95    = if (!is.null(s_B)) s_B$pred_q95_fmt    else NA_character_,
        B_tau         = if (!is.null(s_B)) s_B$tau_fmt         else NA_character_,
        B_width       = if (!is.null(s_B)) round(s_B$pred_median_width, 3L) else NA_real_,
        B_elpd        = if (!is.null(s_B) && !is.na(s_B$elpd)) round(s_B$elpd, 1L) else NA_real_,
        B_elpd_se     = if (!is.null(s_B) && !is.na(s_B$elpd_se)) round(s_B$elpd_se, 1L) else NA_real_,
        B_n_k_high    = if (!is.null(s_B)) s_B$n_k_high else NA_integer_,

        # ── Arm C: federated ─────────────────────────────────────────────────
        C_pred_median = s_C$pred_median_fmt,
        C_pred_q95    = s_C$pred_q95_fmt,
        C_tau         = s_C$tau_fmt,
        C_width       = round(s_C$pred_median_width, 3L),
        C_elpd        = if (!is.na(s_C$elpd)) round(s_C$elpd, 1L) else NA_real_,
        C_elpd_se     = if (!is.na(s_C$elpd_se)) round(s_C$elpd_se, 1L) else NA_real_,
        C_n_k_high    = s_C$n_k_high,

        # ── Differences: federated minus each arm ───────────────────────────
        delta_CA_median = .delta(s_C, s_A, "pred_median_med"),
        delta_CA_q95    = .delta(s_C, s_A, "pred_q95_med"),
        delta_CB_median = .delta(s_C, s_B, "pred_median_med"),
        delta_CB_q95    = .delta(s_C, s_B, "pred_q95_med"),

        # ── Interval ratio: arm_width / C_width  (> 1 = federated is tighter) ──
        ratio_CA = .ratio(s_A, s_C),
        ratio_CB = .ratio(s_B, s_C),

        # ── Normalised shift: (C_median − arm_median) / arm_width ──────────
        norm_shift_CA = .norm_shift(s_A, s_C),
        norm_shift_CB = .norm_shift(s_B, s_C),

        # ── Distributional metrics (A vs C) ──────────────────────────────────
        W2_CA  = .dm_field(dm_CA, "W2"),
        JS_CA  = .dm_field(dm_CA, "JS"),
        OVL_CA = .dm_field(dm_CA, "OVL"),

        # ── Distributional metrics (B vs C) ──────────────────────────────────
        W2_CB  = .dm_field(dm_CB, "W2"),
        JS_CB  = .dm_field(dm_CB, "JS"),
        OVL_CB = .dm_field(dm_CB, "OVL"),

        # ── Distributional metrics (A vs B) ──────────────────────────────────
        W2_AB  = .dm_field(dm_AB, "W2"),
        JS_AB  = .dm_field(dm_AB, "JS"),
        OVL_AB = .dm_field(dm_AB, "OVL")
      ),
      tail_cols
    )

    rows[[length(rows) + 1L]] <- as.data.frame(row, stringsAsFactors = FALSE)
  }
}

comparison_tbl <- if (length(rows) > 0L) {
  tbl <- do.call(rbind, rows)
  rownames(tbl) <- NULL
  tbl
} else {
  message("WARNING: no rows in comparison table — check fitting completed.")
  data.frame()
}


# ── 12. Save and report ───────────────────────────────────────────────────────

saveRDS(
  list(ablation_fits = ablation_results, comparison_tbl = comparison_tbl),
  OUTPUT_FILE
)
message("\nRDS saved to: ", OUTPUT_FILE)

if (nrow(comparison_tbl) > 0L) {
  write.csv(comparison_tbl, CSV_FILE, row.names = FALSE)
  message("CSV saved to: ", CSV_FILE)
}

message("\n", strrep("=", 80))
message("DATA-FORMAT ABLATION — summary tables")
message(strrep("=", 80))
message(
  "\nArms:\n",
  "  A  individual_only — types 4/5: exact + interval-censored freq tables\n",
  "  B  summary_only    — types 1/2/3: median+range, median+IQR, mean+SD\n",
  "  C  federated       — all data formats jointly\n"
)

if (nrow(comparison_tbl) > 0L) {

  # ── Table 1: Predictive summaries ───────────────────────────────────────────
  message("\n=== Table 1: Predictive summaries (days, median [95% CrI]) ===\n")
  cols1 <- c("pathogen", "dist", "n_indiv", "n_sumstat", "n_total",
             "A_pred_median", "B_pred_median", "C_pred_median",
             "delta_CA_median", "delta_CB_median")
  print(comparison_tbl[, intersect(cols1, names(comparison_tbl))],
        row.names = FALSE, right = FALSE)

  message("\n=== Table 2: Predictive 95th percentile (days) ===\n")
  cols2 <- c("pathogen", "dist",
             "A_pred_q95", "B_pred_q95", "C_pred_q95",
             "delta_CA_q95", "delta_CB_q95")
  print(comparison_tbl[, intersect(cols2, names(comparison_tbl))],
        row.names = FALSE, right = FALSE)

  # ── Table 2: Uncertainty and tau ─────────────────────────────────────────────
  message("\n=== Table 3: Posterior uncertainty and heterogeneity tau ===\n")
  message("  width      = 95% CrI width of pred_median\n",
          "  ratio_CA   = A_width / C_width  (> 1 = federated is tighter)\n",
          "  norm_shift = (C_median − arm_median) / arm_width\n")
  cols3 <- c("pathogen", "dist",
             "A_width", "B_width", "C_width",
             "ratio_CA", "ratio_CB",
             "norm_shift_CA", "norm_shift_CB",
             "A_tau", "B_tau", "C_tau")
  print(comparison_tbl[, intersect(cols3, names(comparison_tbl))],
        row.names = FALSE, right = FALSE)

  # ── Table 3: Distributional metrics ──────────────────────────────────────────
  if (COMPUTE_CDF_METRICS) {
    message("\n=== Table 4: Distributional discrepancy metrics ===\n")
    message("  W2   Wasserstein-2 (days); CA = arm C vs A, CB = C vs B, AB = A vs B\n",
            "  JS   Jensen-Shannon divergence (bits); symmetric, bounded [0, 1]\n",
            "  OVL  Overlap coefficient; 1 = identical distributions\n")
    cols4 <- c("pathogen", "dist",
               "W2_CA", "JS_CA", "OVL_CA",
               "W2_CB", "JS_CB", "OVL_CB",
               "W2_AB", "JS_AB", "OVL_AB")
    print(comparison_tbl[, intersect(cols4, names(comparison_tbl))],
          row.names = FALSE, right = FALSE)

    message("\n=== Table 5: Tail probabilities P(T > d days) ===\n")
    tail_col_names <- c("pathogen", "dist",
                        unlist(lapply(TAIL_THRESHOLDS, function(d)
                          c(paste0("ptail_A_", d),
                            paste0("ptail_B_", d),
                            paste0("ptail_C_", d)))))
    print(comparison_tbl[, intersect(tail_col_names, names(comparison_tbl))],
          row.names = FALSE, right = FALSE)
  }

  # ── Table 4: LOO / ELPD ───────────────────────────────────────────────────────
  message("\n=== Table 6: Study-level PSIS-LOO ELPD ===\n")
  message("  n_k_high = studies with Pareto k̂ > 0.7 (LOO reliability flag)\n")
  cols6 <- c("pathogen", "dist",
             "A_elpd", "A_elpd_se", "A_n_k_high",
             "B_elpd", "B_elpd_se", "B_n_k_high",
             "C_elpd", "C_elpd_se", "C_n_k_high")
  print(comparison_tbl[, intersect(cols6, names(comparison_tbl))],
        row.names = FALSE, right = FALSE)
}

message("\n", strrep("=", 80))
message("Done.  Results written to: ", OUTPUT_FILE)
message(strrep("=", 80))
